# -*- coding: utf-8 -*-
"""CSV datacleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13hGTPJGteIYJTTXyv2h8NMGFdeQJm7BF
"""

import pandas as pd
import numpy as np
def clean_data(df):
    print("Initial DataFrame:")
    print(df)
    print()
    df.fillna(method='ffill', inplace=True)
    df.dropna(inplace=True)
    df.drop_duplicates(inplace=True)
    numeric_columns = df.select_dtypes(include=[np.number]).columns
    df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors='coerce')
    print("Cleaned DataFrame:")
    print(df)
    print()
file_path = input("Enter the file path for the CSV file: ")
print(" File has opened successfully")
data = pd.read_csv(file_path)
df = pd.DataFrame(data)
clean_data(df)